### ISSUE TITLE
try with resources not supported on android sdk 9

### ISSUE THREAD

**Issue by Trolldemorted** [Turasa/libsignal-service-java#10]
As [moxie said](https://github.com/WhisperSystems/Signal-Android/issues/6284#issuecomment-281776636), try with resources [are not supported](http://stackoverflow.com/questions/24290830/try-with-resources-are-not-supported-at-this-language-level-android) on[ android sdk 9](https://github.com/WhisperSystems/Signal-Android/blob/1669731329bcc32c84e33035a67a2fc22444c24b/build.gradle#L197), which is the minsdk for Signal-Android.

Since i can build (and run) Signal-Android with your fork, i assume it would crash at runtime on old devices? I am not a gradle expert, can we adjust the gradle build config so that we get errors during build time if something like that happens?

**Comment by Turakar** [comment]
You are right. The source compatibility is set to Java 1.7 in the android/build.gradle, but we have minSdkVersion 9 in the AndroidManifest.xml. As Java versions cannot be mapped to Android versions we need to pass the minimum SDK version to the Android compiler, as it seems like this is ignored at the moment.

**Comment by AsamK** [comment]
minSdkVersion is now 19 so this is not an issue anymore
