### ISSUE TITLE
Are there plans to support profiles?

### ISSUE THREAD

**Issue by thefinn93** [Turasa/libsignal-service-java#14]
Upstream has a bunch of functions related to reading and setting protocols. Are there any plans to add to this fork?

I use this library in [signald](https://github.com/thefinn93/signald), and would like to add support for profiles eventually.

**Comment by Trolldemorted** [comment]
Doesn't setting and reading a profile work already? My Signal-Android uses this fork and it is able to read and set profiles iirc.

**Comment by thefinn93** [comment]
Hrm, perhaps I'll need to do more research then. I noticed the word "profile" appears a lot in the upstream library and nowhere here, and I'm not really sure how to interact with them. Thanks for the info.

**Comment by Trolldemorted** [comment]
https://github.com/Turasa/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageReceiver.java#L113

Github's search function does not work for forks, unfortunately.

**Comment by thefinn93** [comment]
Oh wow thanks.
