### ISSUE TITLE
Publish 2.8.1_unofficial_1 and maybe automate the process?

### ISSUE THREAD

**Issue by thefinn93** [Turasa/libsignal-service-java#17]
Hey there, it seems that version `2.8.1_unofficial_1` isn't published on maven. Would you be willing to spend some time automating the release process so this sort of thing doesn't happen again?

Thanks :)

**Comment by AsamK** [comment]
Pushed 2.9.0 now.
The upload is already quite automated. The annoying thing are the two clicks in the Nexus Repository Manager to release the update...
