### ISSUE TITLE
Please merge from upstream

### ISSUE THREAD

**Issue by thefinn93** [Turasa/libsignal-service-java#19]
Upstream has had a new major features since the last merge on October 9th. Could you merge in from upstream again?

Thanks :)

**Comment by AsamK** [comment]
done, but I haven't tested it yet, apart from compiling ...
For testing you can install it to your local maven repository: `./gradlew installArchives`

**Comment by thefinn93** [comment]
Thanks, sorry for the delay. I got it working with signald, and after some minor changes I seem to be able to send and receive messages. Could you push this update out to maven? That would also resolve #20
