### ISSUE TITLE
Upstream libsignal-service-java appears discontinued

### ISSUE THREAD

**Issue by Trolldemorted** [Turasa/libsignal-service-java#22]
It looks like libsignal-service-java has moved into Signal-Android's repository: https://github.com/signalapp/Signal-Android/blob/master/libsignal/service/build.gradle

Any idea how you will continue? Can you apply commits from that repo easily? Some classes that [exist in the new upstream](https://github.com/signalapp/Signal-Android/tree/master/libsignal/service/src/main/java/org/whispersystems/signalservice/api/storage) are missing here :(

**Comment by AsamK** [comment]
yep, I was just working on this :)

I've copied the commits from the Android repository and pushed them to a new branch:
https://github.com/Turasa/libsignal-service-java/tree/upstream

That branch just contains the upstream code without modifications. The `java` folder contains the same code as the `libsignal/service` folder in Signal-Android.

**Comment by Trolldemorted** [comment]
Great!

Will you introduce your own version numbers and push them to maven?

**Comment by AsamK** [comment]
The signal-service library still has a version number in the Signal-Android repository, though they haven't updated it yet.
For now I'll keep using that version number and just increase the unofficial number in the end. The new version is already pushed to maven as `2.15.3_unofficial_2`
