### ISSUE TITLE
Proxy does not effect

### ISSUE THREAD

**Issue by hoangatpaygate** [Turasa/libsignal-service-java#26]
Hello,
I have tried to use an HTTP proxy but it does not work.
Could you provide some tips to use the proxy?
Another question is that could I use sock proxy?

Thanks

**Comment by AsamK** [comment]
proxy can be configured with java properties

`-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080`
