### ISSUE TITLE
Why do the releases not correspond to commits on this repo?

### ISSUE THREAD

**Issue by matthiasdg** [Turasa/libsignal-service-java#35]
e.g., the tag v2.15.3_unofficial_98 or the corresponding commit can't be checked out. I can of course just download the zip from the release but this feels weird.

**Comment by AsamK** [comment]
If course you can check them out, all the tags are there
https://github.com/Turasa/libsignal-service-java/tags

**Comment by matthiasdg** [comment]
Ok, I see; it's just because they don't belong to any branch. E.g., if you go to https://github.com/Turasa/libsignal-service-java/tree/v2.15.3_unofficial_98, GitHub also shows `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`
So the solution is `git fetch --tags` to have them. Guess I'm just so used to tags on the main branch (which everyone always checks out) 😅

**Comment by AsamK** [comment]
Yeah, I'm rebasing the main branch, because this is more a collection of patches on upstream than a complete fork.
