### ISSUE TITLE
Attachment v3 - How to use it?

### ISSUE THREAD

**Issue by Thireus** [Turasa/libsignal-service-java#37]
Could someone explain how to use attachment v3? cdn0 is being deprecated and I understand there are specific attributes to pass to attachments such as cdnNumber and cdnKey. But it is unclear how to do it.

For ref. this is what I've gathered so far: https://gitlab.com/signald/signald/-/issues/387#note_2126290262

**Comment by AsamK** [comment]
The `SignalServiceMessageSender.getResumableUploadSpec()` method can be used to get the necessary attributes
