### ISSUE TITLE
merge signal-service-java 2.4.4

### ISSUE THREAD

**Issue by Trolldemorted** [Turasa/libsignal-service-java#7]
It would be great if you would merge https://github.com/WhisperSystems/libsignal-service-java/commit/43fc72d2f1245a6ec44bdf88d421ea5dac07436d, since Signal-Android  3.26.0 depends on the changes.

**Comment by AsamK** [comment]
I've merged it, but not yet tested

**Comment by Trolldemorted** [comment]
I have built my signal-android with your current master, and sending/receiving messages appears to work fine. Did not test the anti-censorship measures, though.

**Comment by Trolldemorted** [comment]
aaaand he has changed something again :|

**Comment by Trolldemorted** [comment]
Could you merge 2.5.0? I am really curious whether calling works for slaves.

**Comment by AsamK** [comment]
done. I'm having trouble uploading it to maven, so you need to build it yourself

**Comment by Trolldemorted** [comment]
Webrtc works for slaves!

Could you merge 2.5.10? The dependency for libsignal-protocol-java was changed
